name: Supabase Cloud Pipeline (Dev → Prod)

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy to Development Supabase
        run: |
          echo "🚀 Deploying to Development Environment"
          
          # Link to dev project
          supabase link --project-ref ${{ secrets.SUPABASE_DEV_PROJECT_REF }}
          
          # Show pending migrations
          echo "📋 Pending migrations:"
          supabase migration list --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }} || true
          
          # Deploy database migrations with error handling
          echo "🗄️ Applying database migrations..."
          supabase db push --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }} || {
            echo "⚠️  Some migrations failed - this might be OK if tables already exist"
            echo "Continuing with deployment..."
          }
          
          # Deploy Edge Functions
          echo "⚡ Deploying Edge Functions..."
          supabase functions deploy calloff-crud --project-ref ${{ secrets.SUPABASE_DEV_PROJECT_REF }}
          
          echo "✅ Development deployment complete!"
          echo "Test at: https://pxwtdaqhwzweedflwora.supabase.co"

  deploy-to-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy to Production Supabase
        run: |
          echo "🚀 Deploying to Production Environment"
          
          # Link to production project
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          # Show what will be deployed
          echo "📋 Migrations to be applied:"
          supabase migration list --password ${{ secrets.SUPABASE_DB_PASSWORD }}
          
          # Deploy database migrations
          supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }} || {
            echo "⚠️  Migration failed - attempting to sync production state"
            # Run the fix migration directly if needed
            supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }} --include-all || true
          }
          
          # Deploy Edge Functions
          supabase functions deploy calloff-crud --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          echo "✅ Production deployment complete!"
          echo "Live at: https://brixbdbunhwlhuwunqxw.supabase.co"